### ISSUE TITLE
文档构建失败

### ISSUE THREAD

**Issue by duwenbin0316** [alibaba/ali-react-table#92]
想在内网环境部署一套文档，安装依赖后执行 yarn website:build 失败

错误信息:
```bash
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 行多选 (eval at evalCode (main:121263:13), <anonymous>:7:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at Example (eval at evalCode (main:121263:13), <anonymous>:16:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 列高亮 (eval at evalCode (main:121263:13), <anonymous>:6:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 列高亮 (eval at evalCode (main:121263:13), <anonymous>:6:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 行多选 (eval at evalCode (main:121263:13), <anonymous>:8:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 行详情 (eval at evalCode (main:121263:13), <anonymous>:6:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 行展开 (eval at evalCode (main:121263:13), <anonymous>:21:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 行单选 (eval at evalCode (main:121263:13), <anonymous>:7:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 表格排序 (eval at evalCode (main:121263:13), <anonymous>:11:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 提示信息 (eval at evalCode (main:121263:13), <anonymous>:11:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 树形表格 (eval at evalCode (main:121263:13), <anonymous>:7:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at Object.module.exports.exports.useState (main:282107:277)
    at useTablePipeline (main:14060:2602)
    at 树形可选择表格 (eval at evalCode (main:121263:13), <anonymous>:7:18)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at module.exports.exports.useContext (main:282106:269)
    at main:101928:13638
    at Object.styled.div [as render] (main:101928:14425)
    at a.b.render (main:267312:105)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at module.exports.exports.useContext (main:282106:269)
    at main:101928:13638
    at Object.styled.div [as render] (main:101928:14425)
    at a.b.render (main:267312:105)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at module.exports.exports.useContext (main:282106:269)
    at main:101928:13638
    at Object.styled.div [as render] (main:101928:14425)
    at a.b.render (main:267312:105)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at module.exports.exports.useContext (main:282106:269)
    at main:101928:13638
    at Object.styled.div [as render] (main:101928:14425)
    at a.b.render (main:267312:105)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at module.exports.exports.useContext (main:282106:269)
    at main:101928:13638
    at Object.styled.div [as render] (main:101928:14425)
    at a.b.render (main:267312:105)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282102:327)
    at module.exports.exports.useContext (main:282106:269)
    at main:101928:13638
    at Object.styled.div [as render] (main:101928:14425)
    at a.b.render (main:267312:105)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (main:282072:327)
    at module.exports.exports.useContext (main:282076:269)
    at ee (main:17927:7260)
    at l (main:17927:17561)
    at d (main:267302:498)
    at $a (main:267305:16)
    at a.b.render (main:267310:476)
    at a.b.read (main:267310:18)
    at Object.renderToString (main:267320:364)
    at serverEntry_render (main:303843:395)
(undefined) ./examples/themed-table.tsx 2:181-191
"export 'BaseTable' (imported as '_BaseTable') was not found in 'ali-react-table'
(undefined) ./examples/theme.mdx 1:3520-3529
"export 'BaseTable' was not found in 'ali-react-table'
(undefined) ./src/assets/HippoBaseTable.tsx 1:2584-2593
"export 'BaseTable' was not found in 'ali-react-table'
(undefined) ./src/assets/AntdBaseTable.tsx 1:1404-1413
"export 'BaseTable' was not found in 'ali-react-table'
(undefined) ./src/assets/WebsiteBaseTable.tsx 2:185-194
"export 'BaseTable' was not found in 'ali-react-table'
(undefined) ./src/assets/WebsiteBaseTable.tsx 4:36-45
"export 'BaseTable' was not found in 'ali-react-table'
(undefined) ./examples/biz/remain-matrix.stories.tsx 2:881-888
"export 'Classes' was not found in 'ali-react-table'
(undefined) ./examples/biz/remain-matrix.stories.tsx 2:901-908
"export 'Classes' was not found in 'ali-react-table'
(undefined) ./src/assets/AntdBaseTable.tsx 1:1433-1440
"export 'Classes' was not found in 'ali-react-table'
(undefined) ./src/assets/AntdBaseTable.tsx 1:1456-1463
"export 'Classes' was not found in 'ali-react-table'
(undefined) ./src/theme/ReactLiveScope/index.js 2:104-115
"export 'CrossTable' (imported as '_CrossTable') was not found in 'ali-react-table/pivot'
(undefined) ./examples/others/simple-pivot-table.stories.tsx 1:4147-4157
"export 'CrossTable' was not found in 'ali-react-table/pivot'
(undefined) ./src/theme/ReactLiveScope/index.js 2:258-273
"export 'CrossTreeTable' (imported as '_CrossTreeTable') was not found in 'ali-react-table/pivot'
(undefined) ./examples/others/drill-tree-table/drillable-tree-table.stories.tsx 2:2206-2220
"export 'CrossTreeTable' was not found in 'ali-react-table/pivot'
(undefined) ./examples/themed-table.tsx 2:528-541
"export 'TablePipeline' was not found in 'ali-react-table'
(undefined) ./examples/biz/data-report.stories.tsx 2:220-235
"export 'applyTransforms' was not found in 'ali-react-table'
(undefined) ./examples/biz/ROI-analysis-table.stories.tsx 1:5539-5554
"export 'applyTransforms' was not found in 'ali-react-table'
(undefined) ./examples/others/simple-pivot-table.stories.tsx 1:2341-2355
"export 'buildDrillTree' was not found in 'ali-react-table/pivot'
(undefined) ./examples/others/simple-pivot-table.stories.tsx 1:2957-2971
"export 'buildDrillTree' was not found in 'ali-react-table/pivot'
(undefined) ./examples/biz/data-report.stories.tsx 1:1696-1710
"export 'buildDrillTree' was not found in 'ali-react-table/pivot'
(undefined) ./examples/others/drill-tree-table/models.ts 1:4231-4245
"export 'buildDrillTree' was not found in 'ali-react-table/pivot'
(undefined) ./examples/biz/data-report.stories.tsx 1:1737-1751
"export 'buildRecordMap' was not found in 'ali-react-table/pivot'
(undefined) ./examples/others/drill-tree-table/models.ts 1:4595-4609
"export 'buildRecordMap' was not found in 'ali-react-table/pivot'
(undefined) ./examples/others/simple-pivot-table.stories.tsx 1:3477-3494
"export 'buildRecordMatrix' was not found in 'ali-react-table/pivot'
(undefined) ./examples/pipeline.stories.tsx 1:1383-1395
"export 'collectNodes' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 4:146-158
"export 'collectNodes' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:2480-2492
"export 'collectNodes' was not found in 'ali-react-table'
(undefined) ./examples/others/simple-pivot-table.stories.tsx 1:2507-2534
"export 'convertDrillTreeToCrossTree' was not found in 'ali-react-table/pivot'
(undefined) ./examples/others/simple-pivot-table.stories.tsx 1:3122-3149
"export 'convertDrillTreeToCrossTree' was not found in 'ali-react-table/pivot'
(undefined) ./examples/big-data.stories.tsx 1:4230-4238
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/big-data.stories.tsx 1:7141-7149
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 1:1291-1299
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 4:201-209
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 7:108-116
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:5-13
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:265-273
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:581-589
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:1486-1494
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:1528-1536
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:1595-1603
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:1879-1887
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:2518-2526
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:2617-2625
"export 'features' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 12:2914-2922
"export 'features' was not found in 'ali-react-table'
(undefined) ./src/assets/HippoBaseTable.tsx 4:160-172
"export 'getTreeDepth' was not found in 'ali-react-table'
(undefined) ./src/assets/AntdBaseTable.tsx 3:158-170
"export 'getTreeDepth' was not found in 'ali-react-table'
(undefined) ./examples/biz/data-report.stories.tsx 3:941-951
"export 'isLeafNode' was not found in 'ali-react-table'
(undefined) ./examples/pipeline.stories.tsx 1:1443-1453
"export 'isLeafNode' was not found in 'ali-react-table'
(undefined) ./examples/biz/data-report.stories.tsx 3:67-88
"export 'makeTreeModeTransform' was not found in 'ali-react-table'
(undefined) ./examples/biz/ROI-analysis-table.stories.tsx 1:2236-2241
"export 'proto' was not found in 'ali-react-table'
(undefined) ./examples/biz/ROI-analysis-table.stories.tsx 1:2295-2300
"export 'proto' was not found in 'ali-react-table'
(undefined) ./examples/biz/ROI-analysis-table.stories.tsx 1:2328-2333
"export 'proto' was not found in 'ali-react-table'
(undefined) ./examples/biz/ROI-analysis-table.stories.tsx 1:4566-4571
"export 'proto' was not found in 'ali-react-table'
(undefined) ./examples/biz/remain-matrix.stories.tsx 2:971-976
"export 'proto' was not found in 'ali-react-table'
(undefined) ./src/assets/biz-assets.tsx 2:5302-5307
"export 'proto' was not found in 'ali-react-table'
(undefined) ./examples/biz/ROI-analysis-table.stories.tsx 1:5595-5609
"export 'traverseColumn' was not found in 'ali-react-table'
(undefined) ./examples/themed-table.tsx 2:780-797
"export 'useTablePipeline' (imported as '_useTablePipeline') was not found in 'ali-react-table'
Error: Failed to compile with errors.
    at /Users/duwenbin/component-market/ali-react-table/node_modules/@docusaurus/core/lib/webpack/utils.js:164:24
    at finalCallback (/Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/Users/duwenbin/component-market/ali-react-table/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/duwenbin/component-market/ali-react-table/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/duwenbin/component-market/ali-react-table/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/duwenbin/component-market/ali-react-table/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/duwenbin/component-market/ali-react-table/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/duwenbin/component-market/ali-react-table/node_modules/webpack/lib/Compiler.js:678:31
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website@0.0.0 build: `docusaurus build --no-minify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the website@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/duwenbin/.npm/_logs/2020-10-29T06_22_07_159Z-debug.log
```

**Comment by shinima** [comment]
嗯  昨天加上了 react17 的支持之后，出现了多个 react 版本，我修复一下

**Comment by shinima** [comment]
已在 63928428 中更新

**Comment by duwenbin0316** [comment]
> 已在 [6392842](https://github.com/alibaba/ali-react-table/commit/639284286ad866342174b5df514f285fa1f1a911) 中更新

更新后构建成功了，谢谢～
